[package]
name = "simpletaskmgr"
version = "0.1.0"
edition = "2021"

[dependencies]
floem = "0.2.0"
im = "15.1.0"
procfs = "0.17.0"
users = "0.11.0"

[lib]
name = "simpletaskmgr"
path = "src/lib.rs"

[[bin]]
name = "simpletaskmgr"
path = "src/main.rs"
